/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package talent.show;


import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;

/**
 *
 * @author HP
 */
public class AddSoloFrame extends javax.swing.JFrame implements KeyListener{
    StagePrepFrame pf;
    MainFrame main;
    
    /**
     * Creates new form AddSoloFrame
     * @param mf
     */
    public AddSoloFrame(MainFrame mf) {
        //Color c = new Color(255, 204, 204);
        Color c = new Color(191, 216, 189);
        main = mf;
        initComponents();  
        this.getContentPane().setBackground(c);
        nameText.addKeyListener(this);
        typeList.addKeyListener(this);
        nameSurnameText.addKeyListener(this);
        ageList.addKeyListener(this);
        maleButton.addKeyListener(this);
        femaleButton.addKeyListener(this);
        contactNumberText.addKeyListener(this);
        emailText.addKeyListener(this);
        addApplicantButton.addKeyListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        showName = new javax.swing.JLabel();
        showType = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        typeList = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        nameSurname = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        ageList = new javax.swing.JComboBox<>();
        gender = new javax.swing.JLabel();
        maleButton = new javax.swing.JRadioButton();
        femaleButton = new javax.swing.JRadioButton();
        contactNumber = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        nameSurnameText = new javax.swing.JTextField();
        contactNumberText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        addApplicantButton = new javax.swing.JButton();
        warning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Solo");
        setResizable(false);

        showName.setText("Show Name:");

        showType.setText("Show Type:");

        typeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dance", "Comedy", "Music", "Magic", "Pet", "Skit", "Sports", "Other" }));

        jPanel1.setBackground(new java.awt.Color(221, 231, 199));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(152, 201, 163), 3, true));

        nameSurname.setText("Name Surname:");

        age.setText("Age:");

        ageList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60" }));

        gender.setText("Gender:");

        buttonGroup1.add(maleButton);
        maleButton.setSelected(true);
        maleButton.setText("Male");

        buttonGroup1.add(femaleButton);
        femaleButton.setText("Female");

        contactNumber.setText("Contact Number:");

        email.setText("Email:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(email)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(age)
                        .addGap(18, 18, 18)
                        .addComponent(ageList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gender)
                        .addGap(18, 18, 18)
                        .addComponent(maleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(femaleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameSurname)
                        .addGap(18, 18, 18)
                        .addComponent(nameSurnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(contactNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(contactNumberText)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameSurname)
                    .addComponent(nameSurnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age)
                    .addComponent(ageList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender)
                    .addComponent(maleButton)
                    .addComponent(femaleButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNumber)
                    .addComponent(contactNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        addApplicantButton.setText("PROCEED");
        addApplicantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addApplicantButtonActionPerformed(evt);
            }
        });

        warning.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        warning.setForeground(new java.awt.Color(227, 33, 33));
        warning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showName)
                            .addComponent(showType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(typeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addComponent(addApplicantButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showName)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addApplicantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showType)
                    .addComponent(typeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(warning, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void keyTyped(KeyEvent e)
    {
        //NOT USED
    }
    
    public void keyReleased(KeyEvent e)
    {
        //NOT USED
    }
    
    public void keyPressed(KeyEvent e)
    {
        int keyCode = e.getKeyCode();
        
        if(nameText.hasFocus())
        {
            switch(keyCode)
            {
                case KeyEvent.VK_DOWN: typeList.requestFocus();
                break;
                case KeyEvent.VK_UP: emailText.requestFocus();
                break;
            }
        }else if(typeList.hasFocus())
        {
            if((typeList.getSelectedIndex() == 7 && keyCode == KeyEvent.VK_DOWN) || keyCode == KeyEvent.VK_ENTER)
                nameSurnameText.requestFocus();
            else if((typeList.getSelectedIndex() == 0 && keyCode == KeyEvent.VK_UP) || keyCode == KeyEvent.VK_SHIFT)
                nameText.requestFocus();
        }else if(nameSurnameText.hasFocus())
        {
            switch(keyCode)
            {
                case KeyEvent.VK_DOWN: ageList.requestFocus();
                break;
                case KeyEvent.VK_UP: typeList.requestFocus();
                break;
            }
        }else if(maleButton.hasFocus())
        {
            switch(keyCode)
            {
                case KeyEvent.VK_DOWN: contactNumberText.requestFocus();
                break;
                case KeyEvent.VK_UP: ageList.requestFocus();
                break;
                case KeyEvent.VK_RIGHT: femaleButton.setSelected(true); femaleButton.requestFocus();
                break;
                case KeyEvent.VK_LEFT: femaleButton.setSelected(true); femaleButton.requestFocus();
            }
        }
        else if(femaleButton.hasFocus())
        {
            switch(keyCode)
            {
                case KeyEvent.VK_DOWN: contactNumberText.requestFocus();
                break;
                case KeyEvent.VK_UP: ageList.requestFocus();
                break;
                case KeyEvent.VK_RIGHT: maleButton.setSelected(true); maleButton.requestFocus();
                break;
                case KeyEvent.VK_LEFT: maleButton.setSelected(true); maleButton.requestFocus();
            }
        } else if(ageList.hasFocus())
        {
            if((ageList.getSelectedIndex() == 49 && keyCode == KeyEvent.VK_DOWN) || keyCode == KeyEvent.VK_ENTER)
                maleButton.requestFocus();
            else if((ageList.getSelectedIndex() == 0 && keyCode == KeyEvent.VK_UP) || keyCode == KeyEvent.VK_SHIFT)
                nameSurnameText.requestFocus();
        }else if(contactNumberText.hasFocus())
        {
            switch(keyCode)
            {
                case KeyEvent.VK_DOWN: emailText.requestFocus();
                break;
                case KeyEvent.VK_UP: maleButton.requestFocus();
                break;
            }
        }else if(emailText.hasFocus())
        {
            switch(keyCode)
            {
                case KeyEvent.VK_DOWN: nameText.requestFocus();
                break;
                case KeyEvent.VK_UP: contactNumberText.requestFocus();
                break;
            }
        }
        if(!ageList.hasFocus() && !typeList.hasFocus() && keyCode == KeyEvent.VK_ENTER)
            addApplicantButton.doClick();
    }
    
    private void clear()
    {
      nameText.setText("");
      nameSurnameText.setText("");
      emailText.setText("");
      contactNumberText.setText("");
      typeList.setSelectedIndex(0);
      ageList.setSelectedIndex(0);
      maleButton.setSelected(true);
      femaleButton.setSelected(false);
      warning.setText("");
    }
    
    private void addApplicantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addApplicantButtonActionPerformed
        if(nameText.getText().isEmpty() || nameSurnameText.getText().isEmpty() || emailText.getText().isEmpty() || contactNumberText.getText().isEmpty())
            warning.setText("Fill all fields!");
        else{
            char g;
            if(maleButton.isSelected())
                g = 'M';
            else g = 'F';
                
           ArrayList<Individual_info> ind = new ArrayList();
           Individual_info ind1 = new Individual_info(Integer.parseInt((String) ageList.getSelectedItem()), nameSurnameText.getText(), g,contactNumberText.getText(), emailText.getText());
           ind.add(ind1);
           //ApplicantSys.addSolo(nameText.getText(), (String)typeList.getSelectedItem(), ind);
           pf = new StagePrepFrame(nameText.getText(), (String)typeList.getSelectedItem(), main, ind); 
            pf.setVisible(true);
            //main.setVisible(true);
            this.clear();
            this.dispose();
            
        }
            
    }//GEN-LAST:event_addApplicantButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addApplicantButton;
    private javax.swing.JLabel age;
    private javax.swing.JComboBox<String> ageList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel contactNumber;
    private javax.swing.JTextField contactNumberText;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailText;
    private javax.swing.JRadioButton femaleButton;
    private javax.swing.JLabel gender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton maleButton;
    private javax.swing.JLabel nameSurname;
    private javax.swing.JTextField nameSurnameText;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel showName;
    private javax.swing.JLabel showType;
    private javax.swing.JComboBox<String> typeList;
    private javax.swing.JLabel warning;
    // End of variables declaration//GEN-END:variables
}
